masthead_title: ""
title: "Etherio"
name: &name "Ethereal" # &name is a YAML anchor which can be *referenced later
description: "Etherio Documentation"
logo: "./docs/assets/img/logo.png"
url: "https://www.etherio.net"
baseurl: "/"
repository: "etherio/docs"

encoding: "UTF-8"
locale: "en-US"
timezone: "Asia/Yangon" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

title_separator: "-"
breadcurmbs: true # false (default), true
words_per_minute: 200

comments:
  providers: "staticman" # false (default), "disqus", "facebook", "google-plus", "staticman_v2", "staticman"

staticman:
  allowedFields: ['name', 'email', 'message']
  branch: "master"
  commitMessage: # "New Comment"
  filename: # comment-{@timestamp}
  format: yml
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: # "md5"
  generateFields:
    date:
      type: "date"
      options:
        format: # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"

atom_feed:
  path: # blank (default) use feed.xml

search: true # false (default), true
search_full_content: false # false (default), true
search_provider: lunr # lunr (default), algolia

google_site_verification: "{Google-Site-Verification-Id}"

twitter:
  username: ""
facebook:
  username: ""
  app_id: 
  publisher: 
og_image: "/docs/assets/images/logo.png"

analytics:
  provider: "google-universal"
  google:
    track_id: #UA-XXXXXX-X

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:year/:month/:title
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "community"
  - scope:
      path: "docs",
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: "_posts"
      type: pages
    values:
      layout: single
      author_profile: false
      comments: false
      share: false
      related: true
      sidebar:
        nav: "community"
sass:
  sass_dir: _sass

permalink: /:category/:title/
paginate: 10
paginate_path: /page:num/

include:
  - .htaccess

exclude:
  - Gemfile

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
